version: '3.9'

services:
  soonyang-api:
    image: soonyang-api
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: soonyang-api
    ports:
      - 3000:3000
    environment:
      DB_HOST: soonyang-db
      DB_PORT: 5432
      DB_USER: jindojoon
      DB_PASSWD: 1234
      DB_NAME: soonyang
    depends_on:
      - soonyang-db
  soonyang-db:
    image: postgres
    container_name: soonyang-db
    environment:
      POSTGRES_DB: soonyang
      POSTGRES_USER: jindojoon
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
